### libcurl ###

if(BUILD_CLIENT)
  if(USE_INTERNAL_CURL)
    find_package(CURL CONFIG REQUIRED)
    if(TARGET CURL::libcurl)
      set_target_properties(CURL::libcurl PROPERTIES IMPORTED_GLOBAL True)
    endif()
  else()
    find_package(CURL REQUIRED)
    if(TARGET CURL::libcurl)
      set_target_properties(CURL::libcurl PROPERTIES IMPORTED_GLOBAL True)
      if(WIN32)
        target_link_libraries(CURL::libcurl INTERFACE ws2_32 crypt32)
      endif()
    endif()
  endif()
endif()
